PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://semantics.id/ns/example/movie#>
CONSTRUCT { ?actor :playsIn ?movie . }
WHERE { ?movie rdf:type :Movie ;
               :hasActor ?actor .
        ?actor rdf:type :Actor .
}